Display

<Display>
    BoxLayout:
        orientation: "vertical"
        Label:
            text: "Cheese Block"
        Image:
            id: image
            source: root.display_image()
            #source: "SpongebobChair.jpg"
            size_hint: 1, 6
        BoxLayout:
            Button:
                text: "<<<"
                on_release(self):

            Button
                text: ">>>"

